### ISSUE TITLE
Human_detection errors

### ISSUE THREAD

**Issue by esrocom** [danielkaldheim/ha_airstage#17]
I get human_detection errors when I change whatever setting on a unit. Whether it is changing the target temp or operational mode.

"Failed to call service climate/set_temperature. 'AirstageAC' object has no attribute 'get_human_detection'" pop-up.

This happens on al my fujitsu airco's (5 in total).

Here's my logging:
AttributeError: 'AirstageAC' object has no attribute 'get_human_detection'
2023-10-31 09:14:53.134 ERROR (MainThread) [homeassistant.components.binary_sensor] Error while setting up fujitsu_airstage platform for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 367, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 752, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1057, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 779, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 879, in _async_write_ha_state
    state, attr = self._async_generate_attributes()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 820, in _async_generate_attributes
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 785, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/binary_sensor/__init__.py", line 218, in state
    if (is_on := self.is_on) is None:
                 ^^^^^^^^^^
  File "/config/custom_components/fujitsu_airstage/binary_sensor.py", line 59, in is_on
    return self._ac.get_human_detection() == constants.BooleanDescriptors.ON

**Comment by danielkaldheim** [comment]
I removed this in version [v1.1.1](https://github.com/danielkaldheim/ha_airstage/releases/tag/v1.1.1), and it's probably just the sensor still left in home assistant. If you're on a newer version than 1.1.1 you can safely delete this sensor.

**Comment by esrocom** [comment]
Unfortunately I already updated to your newest version which doens't give errors anymore so I cannot reproduce. The main thing is that all works fine now.

**Comment by danielkaldheim** [comment]
Allright, let me know if the issue surface again!
